# Generated by Django 3.1.1 on 2021-04-05 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyVerseFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(blank=True)),
                ('results_path', models.TextField(blank=True)),
                ('friendly_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'CyVerse Folder',
            },
        ),
        migrations.AddField(
            model_name='cyverseaccount',
            name='default_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_folder', to='app.cyversefolder'),
        ),
        migrations.AddField(
            model_name='cyverseaccount',
            name='folders',
            field=models.ManyToManyField(blank=True, to='app.CyVerseFolder'),
        ),
    ]
